# -*- coding: utf-8 -*-
"""hora_da_pratica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dfR-Ywa5q5rj2EkeMgGDWlJySHXhY9S3

# Sobre o notebook

A "hora da prática" é uma atividade do curso de Python para Data Science da Alura que contém diversos desafios envolvendo os aprendizados de cada aula.

O notebook "hora da pratica" é um notebook construído com espaço para as células dos desafios propostos no curso, com ele você tem espaço para construir e executar suas soluções

## Aula 1 - Introdução ao Python

### Questão 1

Imprima a frase `Escola de Dados da Alura!`
"""

print("Escola de Dados da Alura!")

"""### Questão 2
Imprima na tela seu nome e seu sobrenome seguindo a estrutura abaixo:
```
Nome: [seu nome]
Sobrenome: [seu sobrenome]
```

"""

print("Nome: Matheus")
print("Sobrenome: Folle")

"""### Questão 3
Imprima o seu primeiro nome letra a letra. Por exemplo, nome é Mirla, então eu obtenho a seguinte saída:
```
M
I
R
L
A
```

"""

print("M")
print("A")
print("T")
print("H")
print("E")
print("U")
print("S")

"""### Questão 4
Imprima o dia do seu nascimento em formato `dia mês ano`. Os valores de dia e ano não podem estar entre aspas. O formato deve estar como no exemplo, supondo uma data de aniversário dia 28 de fevereiro de 2003:
```
28 fevereiro 2003
```
"""

print(20, "Novembro", 2025)

"""### Questão 5
Imprima em um único print o atual ano que você está fazendo esse curso, o valor do ano deve ser um dado numérico. A saída do print deve ser a seguinte:
```
Ano atual: [ano]
```

"""

print("Ano atual: 2025")

"""## Aula 2 - Manipulando dados no Python

### Coleta e amostragem de dados

#### Questão 1
Crie um programa que solicite à pessoa usuária digitar seu nome, e imprima “Olá, [nome]!”.
"""

nome = input("Digite seu nome: ")
print(f"Olá, {nome}")

"""#### Questão 2
Crie um programa que solicite à pessoa usuária digitar seu nome e idade, e imprima “Olá, [nome], você tem [idade] anos.”.
"""

nome = input("Digite seu nome: ")
idade = input("Digite sua idade: ")
print(f"Olá, {nome}, você tem {idade} anos.")

"""#### Questão 3
Crie um programa que solicite à pessoa usuária digitar seu nome, idade e altura em metros, e imprima “Olá, [nome], você tem [idade] anos e mede [altura] metros!”.
"""

nome = input("Digite seu nome: ")
idade = input("Digite sua idade: ")
altura = input("Digite sua altura: ")
print(f"Olá, {nome}, você tem {idade} anos e mede {altura} metros!")

"""### Calculadora com operadores

#### Questão 1

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a soma dos dois valores.
"""

n1 = int(input("Digite o primeiro valor: "))
n2 = int(input("Digite o segundo valor: "))
soma = n1 + n2
print(soma)

"""#### Questão 2
Crie um programa que solicite três valores numéricos à pessoa usuária e imprima a soma dos três valores.
"""

n1 = int(input("Digite o primeiro valor: "))
n2 = int(input("Digite o segundo valor: "))
n3 = int(input("Digite o terceiro valor: "))
soma = n1 + n2 + n3
print(soma)

"""#### Questão 3
Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a subtração do primeiro pelo o segundo valor.
"""

n1 = int(input("Digite o primeiro valor: "))
n2 = int(input("Digite o segundo valor: "))
sub = n1 - n2
print(sub)

"""#### Questão 4

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a multiplicação dos dois valores.

"""

n1 = int(input("Digite o primeiro valor: "))
n2 = int(input("Digite o segundo valor: "))
multi = n1 * n2
print(multi)

"""#### Questão 5

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e realize a divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.

"""

n1 = int(input("Digite o primeiro valor: "))
n2 = int(input("Digite o segundo valor (não pode ser 0): "))
div = n1 / n2
print(div)

"""#### Questão 6

Crie um programa que solicite dois valores numéricos, um operador e uma potência, e realize a exponenciação entre esses dois valores.

"""

n1 = int(input("Digite o primeiro valor: "))
n2 = int(input("Digite o segundo valor: "))
exp = n1 ** n2
print(exp)

"""#### Questão 7
Crie um programa que solicite dois valores numéricos, um numerador e um denominador e realize a divisão inteira entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.
"""

n1 = int(input("Digite o primeiro valor: "))
n2 = int(input("Digite o segundo valor (não pode ser 0): "))
div_int = n1 // n2
print(div_int)

"""#### Questão 8

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e retorne o resto da divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.
"""

n1 = int(input("Digite o primeiro valor: "))
n2 = int(input("Digite o segundo valor (não pode ser 0): "))
resto = n1 % n2
print(resto)

"""#### Questão 9

Crie um código que solicita 3 notas de um estudante e imprima a média das notas.
"""

nota1 = int(input("Informe a primeira nota: "))
nota2 = int(input("Informe a segunda nota: "))
nota3 = int(input("Informe a terceira nota: "))
print(f"Média: {(nota1 + nota2 + nota3) / 3}")

"""#### Questão 10

Crie um código que calcule e imprima a média ponderada dos números 5, 12, 20 e 15 com pesos respectivamente iguais a 1, 2, 3 e 4.
"""

n1 = 5
n1_peso = 1
n2 = 12
n2_peso = 2
n3 = 20
n3_peso = 3
n4 = 15
n4_peso = 4

ponde = ((n1 * n1_peso) + (n2 * n2_peso) + (n3 * n3_peso) + (n4 * n4_peso)) / 4
print(ponde)

"""### Editando textos

#### Questão 1

Crie uma variável chamada “`frase`” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase na tela.
"""

frase = str("Eu gosto de Ciência de Dados")
print(frase)

"""#### Questão 2
Crie um código que solicite uma frase e depois imprima a frase na tela.
"""

frase = str(input("Informe a frase: "))
print(frase)

"""#### Questão 3

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras maiúsculas.
"""

frase = str(input("Informe a frase: "))
print(frase.upper())

"""#### Questão 4

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras minúsculas.
"""

frase = str(input("Informe a frase: "))
print(frase.lower())

"""#### Questão 5

Crie uma variável chamada “`frase`” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase sem espaços em branco no início e no fim.
"""

frase = " Original e bem visto "
print(frase.strip())

"""#### Questão 6

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim.
"""

frase = str(input("Informe a frase: "))
print(frase.strip())

"""#### Questão 7


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim e em letras minúsculas.
"""

frase = str(input("Informe a frase: "))
print(frase.strip().lower())

"""#### Questão 8

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “`e`” trocadas pela letra “`f`”.
"""

frase = str(input("Informe a frase: "))
print(frase.replace("e", "f"))

"""#### Questão 9


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “`a`” trocadas pela caractere  “`@`”.
"""

frase = str(input("Informe a frase: "))
print(frase.replace("a", "@"))

"""#### Questão 10


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as consoantes “`s`” trocadas pelo caractere  “`$`”.
"""

frase = str(input("Informe a frase: "))
print(frase.replace("s", "$"))

"""## Aula 3 - Estruturas condicionais

### Aquecendo na programação

#### Questão 1
Escreva um programa que peça à pessoa usuária para fornecer dois números e exibir o número maior.
"""

n1 = input("Informe o primeiro número: ")
n2 = input("Informe o segundo número: ")
if n1 > n2:
  print(n1)
else:
  print(n2)

"""#### Questão 2
Escreva um programa que solicite o percentual de crescimento de produção de uma empresa e informe se houve um crescimento (porcentagem positiva) ou decrescimento (porcentagem negativa).
"""

crescimento = int(input("Digite o percentual: "))
if crescimento > 0:
  print("Positivo, crescimento!")
else:
  print("Negativo, decrescimento!")

"""#### Questão 3
Escreva um programa que determine se uma letra fornecida pela pessoa usuária é uma vogal ou consoante.
"""

letra = str(input("Informe uma letra: "))
if letra in "aeiou":
  print("Vogal!")
else:
  print("Consoante!")

"""#### Questão 4
Escreva um programa que leia valores médios de preços de um modelo de carro por 3 anos consecutivos e exiba o valor mais alto e mais baixo entre esses três anos.
"""

valores = [
    float(input("Informe o valor médio no primeiro ano: ")),
    float(input("Informe o valor médio no segundo ano: ")),
    float(input("Informe o valor médio no terceiro ano: "))
]

print(min(valores))
print(max(valores))

valor1 = float(input("Informe o valor médio no primeiro ano: "))
valor2 = float(input("Informe o valor médio no segundo ano: "))
valor3 = float(input("Informe o valor médio no terceiro ano: "))
if valor1 > valor2 and valor1 > valor3:
  print(valor1)
elif valor2 > valor1 and valor2 > valor3:
  print(valor2)
else:
  print(valor3)

if valor1 < valor2 and valor1 < valor3:
  print(valor1)
elif valor2 < valor1 and valor2 < valor3:
  print(valor2)
else:
  print(valor3)

v1 = float(input("Ano 1: "))
v2 = float(input("Ano 2: "))
v3 = float(input("Ano 3: "))

maior = v1
if v2 > maior: maior = v2
if v3 > maior: maior = v3

menor = v1
if v2 < menor: menor = v2
if v3 < menor: menor = v3

print("Maior:", maior)
print("Menor:", menor)

"""#### Questão 5
Escreva um programa que pergunte sobre o preço de três produtos e indique qual é o produto mais barato para comprar.
"""

23
produtos = [
  float(input("Produto 1: ")),
  float(input("Produto 2: ")),
  float(input("Produto 3: "))
]

print(f"O produto mais barato custa ", min(produtos))

"""#### Questão 6
Escreva um programa que leia três números e os exiba em ordem decrescente.
"""

numeros = [
    float(input("Número 1: ")),
    float(input("Número 2: ")),
    float(input("Número 3: "))
]

# print(sorted(numeros, reverse=True))

numeros.sort(reverse=True)
print(numeros)

"""#### Questão 7
Escreva um programa que pergunte em qual turno a pessoa usuária estuda ("manhã", "tarde" ou "noite") e exiba a mensagem "Bom Dia!", "Boa Tarde!", "Boa Noite!", ou "Valor Inválido!", conforme o caso.
"""

valores = input("Digite o turno em que você estuda: ").lower()

if "manhã" in valores:
  print("Bom dia!")
elif "tarde" in valores:
  print("Boa tarde!")
elif "noite" in valores:
  print("Boa noite!")
else:
  print("Valor inválido!")

"""#### Questão 8
Escreva um programa que peça um número inteiro à pessoa usuária e determine se ele é par ou ímpar. Dica: Você pode utilizar o operador módulo `%`.
"""

n = int(input("Digite um número inteiro para descobrir se é par ou ímpar: "))
if n % 2 == 0:
  print("Número par")
else:
  print("Número ímpar")

"""#### Questão 9
Escreva um programa que peça um número à pessoa usuária e informe se ele é inteiro ou decimal.
"""

n = float(input("Informe um número: "))

if n.is_integer():
  print("Inteiro")
else:
  print("Decimal")

n = float(input("Informe um número: "))

if n == int(n):
    print("Inteiro")
else:
    print("Decimal")

"""### Momento dos projetos

#### Questão 10
Um programa deve ser escrito para ler dois números e, em seguida, perguntar à pessoa usuária qual operação ele deseja realizar. O resultado da operação deve incluir informações sobre o número - se é par ou ímpar, positivo ou negativo e inteiro ou decimal.
"""

n1 = float(input("Informe o primeiro número: "))
n2 = float(input("Informe o segundo número: "))

print("Qual operação você deseja verificar?")
print("1-Par ou ímpar")
print("2-Positivo ou negativo")
print("3-Inteiro ou decimal")
ops = input("Digite o número aqui: ")

if "1" in ops:
  if n1 % 2 == 0:
    print("N1 Par")
  else:
    print("N1 Ímpar")
  if n2 % 2 == 0:
    print("N2 Par")
  else:
    print("N2 Ímpar")

elif "2" in ops:
  if n1 > 0:
    print("N1 é positivo")
  elif n1 < 0:
    print("N1 é negativo")
  else:
    print("N1 é neutro")
  if n2 > 0:
    print("N2 é positivo")
  elif n2 < 0:
    print("N2 é negativo")
  else:
    print("N2 é neutro")

elif ("3") in ops:
  if n1.is_integer():
    print("N1 Inteiro")
  else:
    print("N1 Decimal")

  if n2.is_integer():
    print("N2 Inteiro")
  else:
    print("N2 Decimal")

else:
  print("Alternativa inválida")

n1 = float(input("Informe o primeiro número: "))
n2 = float(input("Informe o segundo número: "))

print("Qual operação você deseja verificar?")
print("1-Par ou ímpar")
print("2-Positivo ou negativo")
print("3-Inteiro ou decimal")
ops = input("Digite o número aqui: ")

if ops == "1":
    if n1 % 2 == 0:
        print("N1 Par")
    else:
        print("N1 Ímpar")

    if n2 % 2 == 0:
        print("N2 Par")
    else:
        print("N2 Ímpar")

elif ops == "2":
    if n1 > 0:
        print("N1 é positivo")
    elif n1 < 0:
        print("N1 é negativo")
    else:
        print("N1 é neutro")

    if n2 > 0:
        print("N2 é positivo")
    elif n2 < 0:
        print("N2 é negativo")
    else:
        print("N2 é neutro")

elif ops == "3":
    if n1.is_integer():
        print("N1 Inteiro")
    else:
        print("N1 Decimal")

    if n2.is_integer():
        print("N2 Inteiro")
    else:
        print("N2 Decimal")

else:
    print("Alternativa inválida")

"""#### Questão 11
Escreva um programa que peça à pessoa usuária três números que representam os lados de um triângulo. O programa deve informar se os valores podem ser utilizados para formar um triângulo e, caso afirmativo, se ele é equilátero, isósceles ou escaleno. Tenha em mente algumas dicas:
- Três lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro;
- Triângulo Equilátero: três lados iguais;
- Triângulo Isósceles: quaisquer dois lados iguais;
- Triângulo Escaleno: três lados diferentes;

"""

lado1 = float(input("Informe o primeiro lado do triângulo: "))
lado2 = float(input("Informe o segundo lado do triângulo: "))
lado3 = float(input("Informe o terceiro lado do triângulo: "))

if lado1 + lado2 > lado3 and lado2 + lado3 > lado1 and lado1 + lado3 > lado2:
  print("Triângulo verificado")

  if lado1 == lado2 == lado3:
    print("Equilátero")
  elif lado1 == lado2 or lado1 == lado3 or lado2 == lado3:
    print("Isósceles")
  else:
    print("Escaleno")

else:
  print("Triângulo inválido")

"""#### Questão 12
Um estabelecimento está vendendo combustíveis com descontos variados. Para o etanol, se a quantidade comprada for até 15 litros, o desconto será de 2% por litro. Caso contrário, será de 4% por litro. Para o diesel, se a quantidade comprada for até 15 litros, o desconto será de 3% por litro. Caso contrário, será de 5% por litro. O preço do litro de diesel é R\$ 2,00 e o preço do litro de etanol é R\$ 1,70. Escreva um programa que leia a quantidade de litros vendidos e o tipo de combustível (E para etanol e D para diesel) e calcule o valor a ser pago pelo cliente. Tenha em mente algumas dicas:

- O do valor do desconto será a multiplicação entre preço do litro, quantidade de litros e o valor do desconto.
- O valor a ser pago por um cliente será o resultado da multiplicação do preço do litro pela quantidade de litros menos o valor de desconto resultante do cálculo.

"""

escolha = str(input("D para diesel e G para gasolina: "))
quantidade = float(input("Informe a quantidade de combustível: "))
if escolha == "D" or escolha == "d":
  preco = 2.00
  if quantidade > 15:
    desconto = preco * quantidade * 0.05
  else:
    desconto = preco * quantidade * 0.02
  print(f"{(preco * quantidade) - desconto}")
else:
  preco = 1.70
  if quantidade > 15:
    desconto = preco * quantidade * 0.04
  else:
    desconto = preco * quantidade * 0.02
  print(f"{(preco * quantidade) - desconto}")

"""#### Questão 13
Em uma empresa de venda de imóveis você precisa criar um código que analise os dados de vendas anuais para ajudar a diretoria na tomada de decisão. O código precisa coletar os dados de quantidade de venda durante os anos de 2022 e 2023 e fazer um cálculo de variação percentual. A partir do valor da variação, deve ser enviada às seguintes sugestões:
- Para variação acima de 20%: bonificação para o time de vendas.
- Para variação entre 2% e 20%: pequena bonificação para time de vendas.
- Para variação entre 2% e -10%: planejamento de políticas de incentivo às vendas.
- Para bonificações abaixo de -10%: corte de gastos.

"""

vendas_22 = float(input("Digite a quantidade de vendas no ano de 2022: "))
vendas_23 = float(input("Digite a quantidade de vendas no ano de 2023: "))

variacao = (vendas_23 - vendas_22) / vendas_22 * 100
print(variacao)

if variacao >= 20:
  print("Bonificação para o time de vendas")
elif 2 < variacao < 20:
  print("Pequena bonificação para time de vendas")
elif 2 > variacao >= -10:
  print("Planejamento de políticas de incentivo às vendas")
else:
  print("Corte de gastos")

a2023 = float(input("Vendas de 2023: "))
a2022 = float(input("Vendas de 2022: "))
variacao = (a2023 - a2022) / a2022 * 100
print(f"{variacao:.2f}")
if variacao <= -10:
  print("Corte de gastos.")
elif variacao > -10 and variacao < 2:
  print("Planejamento de políticas de incentivo às vendas.")
elif variacao == 2 and variacao < 20:
  print("Pequena bonificação para time de vendas.")
else:
  print("Bonificação para o time de vendas.")

"""## Aula 4 - Estruturas de repetição

### Aquecendo na programação

#### Questão 1
Escreva um programa que peça dois números inteiros e imprima todos os números inteiros entre eles.
"""

n1 = int(input("Informe o primeiro número: "))
n2 = int(input("Informe o segundo número: "))

for valor in range(n1, n2):
  print(valor)

"""#### Questão 2
Escreva um programa para calcular quantos dias levará para a colônia de uma bactéria A ultrapassar ou igualar a colônia de uma bactéria B, com base nas taxas de crescimento de 3% e 1,5% respectivamente. Considere que a colônia A inicia com 4 elementos e a colônia B com 10 elementos.
"""

colonia_a = 4
colonia_b = 10
dia = 0

while colonia_b >= colonia_a:
  colonia_a *= 1.03
  print(f"A:{colonia_a}")
  colonia_b *= 1.015
  print(f"B:{colonia_b}")
  dia = dia + 1
print(f"Dias: {dia}")

"""#### Questão 2
Escreva um programa para calcular quantos dias levará para a colônia de uma bactéria A ultrapassar ou igualar a colônia de uma bactéria B, com base nas taxas de crescimento de 3% e 1,5% respectivamente. Considere que a colônia A inicia com 4 elementos e a colônia B com 10 elementos.
"""

colonia_a = 4
colonia_b = 10

taxa_a = 1.03
taxa_b = 1.015

dia = 1

while colonia_a < colonia_b:
  dia += 1
  colonia_a *= taxa_a
  colonia_b *= taxa_b
  print(f"Colônia A: {colonia_a}\nColônia B: {colonia_b}")
  print(f"Dia: {dia}")

"""#### Questão 3
Para tratar uma quantidade de 15 dados de avaliações de pessoas usuárias de um serviço da empresa, precisamos verificar se as notas são válidas. Então, escreva um programa que vai receber a nota de 0 a 5 de todos os dados e verificar se é um valor válido. Caso seja inserido uma nota acima de 5 ou abaixo de 0, repita até que a pessoa usuária insira um valor válido.
"""

notas_validas = []

for i in range(1, 16):
  while True:
    try:
      nota = float(input(f"Digite a {i}ª nota (de 0 a 5): "))
      if 0 <= nota <= 5:
        notas_validas.append(nota)
        print("Nota adicionada.")
        break
      else:
        print("Valor inválido. A nota deve estar entre 0 e 5.")
    except ValueError:
        print("Entrada inválida. Por favor, digite um número válido.")

  print(f"Notas coletadas: {notas_validas}")

for dados in range(1, 16):
  nota = int(input("Informe uma nota de 0 a 5: "))
  while nota < 0 or nota > 5:
    nota = int(input("Informe uma nota de 0 a 5: "))

"""#### Questão 4
Desenvolva um programa que leia um conjunto indeterminado de temperaturas em Celsius e faça uma análise. Portanto, escreva um programa que leia temperaturas e informe a média delas. A leitura deve ser encerrada ao ser enviado o valor -273°C.
"""

temperaturas = []
condicao = True

while condicao:
  temperatura = float(input(f"Digite a temperatura {len(temperaturas)}: "))
  if temperatura != -273:
    temperaturas.append(temperatura)
  else:
    condicao = False
media = (sum(temperaturas) / len(temperaturas))
print(f"A média foi: {media}")
print("Fim do programa.")

contador = 0
soma = 0
while contador >= 0:
    temperatura = int(input("Digite uma temperatura em Celsius: "))
    if temperatura == -273:
      break
    soma += temperatura
    contador += 1
print(f"Média: {soma/contador}")

"""#### Questão 5
Escreva um programa que calcule o fatorial de um número inteiro fornecido pela pessoa usuária. O fatorial de um número inteiro é a multiplicação desse número por todos os seus antecessores até o número 1. Por exemplo, o fatorial de 5 é 5 x 4 x 3 x 2 x 1 = 120.
"""

program = True
while program:
  entrada = int(input("Informe um número para calcular seu fatorial: "))
  soma = 1
  while entrada < 0:
    entrada = int(input("Informe um número para calcular seu fatorial: "))
  for i in range(1, entrada + 1):
    soma *= i
  print(f"O fatorial de {entrada} é {soma}!")
  sair = int(input("Digite 0 para sair ou 1 para calcular novamente: "))
  if sair == 0:
    print("Fim do programa.")
    program = False

num = int(input("Informe um número: "))
fat = 1

for i in range(1, num + 1):
  fat *= i

print(f"O fatorial de {num} é {fat}")

entrada = int(input("Informe quantos fatoriais você deseja calcular: "))
fat = 1
for tentativa in range(1, entrada + 1):
  num = int(input("Informe o número para calcular o seu fatorial: "))
  for multiplicador in range(1, num + 1):
    fat *= multiplicador
  print(f"O fatorial de {num} é {fat}")

"""### Momento dos projetos

#### Questão 6
Escreva um programa que gere a tabuada de um número inteiro de 1 a 10, de acordo com a escolha da pessoa usuária. Como exemplo, para o número 2, a tabuada deve ser mostrada no seguinte formato:
```
Tabuada do 2:
2 x 1 = 2
2 x 2 = 4
[...]
2 x 10 = 20
```
"""

num = int(input("Digite o número para obter a tabuada: "))
i = 1
for i in range(1, 11):
  res = num * i
  print(f"{num} x {i} = {res}")

"""#### Questão 7
Os números primos possuem várias aplicações dentro da Ciência de Dados, por exemplo, na criptografia e segurança. Um número primo é aquele que é divisível apenas por um e por ele mesmo. Faça um programa que peça um número inteiro e determine se ele é ou não um número primo.
"""

inteiro = int(input("Digite um número inteiro para descobrir se é ou não primo: "))
primo = True
for i in range(2, inteiro):
  if inteiro % i == 0:
    primo = False
print(primo)

"""#### Questão 8
Vamos entender a distribuição de idades de pensionistas de uma empresa de previdência. Escreva um programa que leia as idades de uma quantidade não informada de clientes e mostre a distribuição em intervalos de [0-25], [26-50], [51-75] e [76-100]. Encerre a entrada de dados com um número negativo.
"""

entrada = 0
faixa1 = 0
faixa2 = 0
faixa3 = 0
faixa4 = 0
while entrada != -1:
  print("Bem-vindo ao assistente de idades.")
  idade = int(input("Olá, a seguir, informe a sua idade: "))
  if idade >= 0 and idade <= 25:
    faixa1 += 1
  elif idade >= 26 and idade <= 50:
    faixa2 += 1
  elif idade >= 51 and idade <= 75:
    faixa3 += 1
  elif idade >= 76 and idade <= 100:
    faixa4 += 1
  else:
    print("Idade fora do intervalo.")
  entrada = int(input("Para sair digite -1, para continuar digite 2: "))

print(f"Faixa 1: {faixa1}\nFaixa 2: {faixa2}\nFaixa 3: {faixa3}\nFaixa 4: {faixa4}")

"""#### Questão 9
Em uma eleição para gerência em uma empresa com 20 funcionários, existem quatro candidatos. Escreva um programa que calcule o vencedor da eleição. A votação ocorreu da seguinte maneira:
- Cada funcionário votou em um dos quatro candidatos (representados pelos números 1, 2, 3 e 4).
- Também foram contabilizados os votos nulos (representado pelo número 5) e os votos em branco (representado pelo número 6).

Ao final da votação, o programa deve exibir o total de votos para cada candidato, o número de votos nulos e o número de votos em branco. Além disso, deve calcular e exibir a porcentagem de votos nulos em relação ao total de votos e a porcentagem de votos em branco em relação ao total de votos.
"""

votacao = 0
voto = -1
voto1 = 0
voto2 = 0
voto3 = 0
voto4 = 0
voto5 = 0
voto6 = 0

for votacao in range(1, 6):
  voto = int(input("Digite o número correspondente ao seu voto, as opções são: \n1 (Lourival)\n2 (Sardinha)\n3 (Loureiro)\n4 (Carlinhos)\n5 (Nulo)\n6 (Branco)\n"))
  if voto < 1 or voto > 6:
    print("Opção inválida")
  elif voto == 1:
    voto1 += 1
  elif voto == 2:
    voto2 += 1
  elif voto == 3:
    voto3 += 1
  elif voto == 4:
    voto4 += 1
  elif voto == 5:
    voto5 += 1
  elif voto == 6:
    voto6 += 1

porcentagem_nulos_relacao = (voto5/len(range(1, 6)))*100
porcentagem_brancos_relacao = (voto6/len(range(1, 6)))*100

print(f"A porcentagem de votos nulos foi {porcentagem_nulos_relacao}")
print(f"A porcentagem de votos brancos foi {porcentagem_brancos_relacao}")

"""## Aula 5 - Estruturas de dados

### Aquecendo na programação

#### Questão 1
Faça um programa que tenha a seguinte lista contendo os valores de gastos de uma empresa de papel `[2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]`. Com esses valores, faça um programa que calcule a média de gastos. Dica, use as funções built-in [`sum()`](https://docs.python.org/3/library/functions.html#sum) e [`len()`](https://docs.python.org/3/library/functions.html#len).
"""

lista = [2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]

media = sum(lista)/len(lista)

print(f"A média dos valores da lista é {media}")

"""#### Questão 2
 Com os mesmos dados da questão anterior, defina quantas compras foram acima de 3000 reais e calcule a porcentagem quanto ao total de compras.
"""

compras = [2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]
maior = []
porcentagem = 0

for compra in compras:
  if compra >= 3000:
    maior.append(compra)
porcentagem = (len(maior) / len(compras)) * 100
print(f"A porcentagem de compras maior que 3.000 é: {porcentagem}%")

"""#### Questão 3
Faça um código que colete em uma lista 5 números inteiros quaisquer e imprima a lista. Exemplo: `[1,4,7,2,4]`.
"""

lista = []
for i in range(1, 6):
  inteiro = int(input(f"Informe o {i}º número da lista: "))
  lista.append(inteiro)
print(lista)

"""#### Questão 4
Colete novamente 5 inteiros e imprima a lista em ordem inversa à enviada.
"""

lista = []
for i in range(1, 6):
  inteiro = int(input(f"Informe o {i}º número da lista: "))
  lista.append(inteiro)
lista.reverse()
lista

"""#### Questão 5
Faça um programa que, ao inserir um número qualquer, criará uma lista contendo todos os números primos entre 1 e o número digitado.
"""

primos = []
numero_qualquer = int(input("Escreva um número qualquer para descobrir os primos entre 0 e ele mesmo: "))

while numero_qualquer <= 0:
  numero_qualquer = int(input("Escreva um número qualquer para descobrir os primos entre 0 e ele mesmo: "))

for n in range(2, numero_qualquer + 1):
  primo = True
  for i in range(2, n):
    if n % i == 0:
      primo = False
      break
  if primo:
    primos.append(n)
primos

lista = []
primo = False
valor = int(input("Informe o número "))

for n in range(2, valor + 1):
  primo = True
  for i in range(2, n):
    if n % i == 0:
      primo = False
      break
  if primo:
    lista.append(n)
lista

primos = []
primo = True

fator = int(input("Informe um número inteiro para que possamos mostrar os números primos no intervalo dele! "))

for n in range(2, fator + 1):
  primo = True
  for i in range(2, n):
    if n % i == 0:
      primo = False
      break
  if primo:
    primos.append(n)
primos

numeros_primos = []

fator = int(input("Digite o número para descobrir seus elementos primos: "))

while fator <= 0:
  fator = int(input("Digite o número para descobrir seus elementos primos: "))

for i in range(2, fator+1):
  primo = True
  for n in range(2, i):
    if i % n == 0:
      primo = False
      break
  if primo:
    numeros_primos.append(i)
numeros_primos

numeros_primos = []
valor = int(input("Informe um valor para descobrir os primos entre 1 e valor: "))
while valor <= 0:
  valor = int(input("Erro! Informe um valor para descobrir os primos entre 1 e valor: "))

if valor >= 1:
  for n in range(2, valor + 1):
    eh_primo = True
    for i in range(2, n):
      if n % i == 0:
        eh_primo = False
        break
    if eh_primo:
      numeros_primos.append(n)
numeros_primos

lista = []

valor = int(input("Informe um número para criar uma lista contendo todos os números primos entre 1 e o número digitado: "))

for n in range(2, valor+1):
  eh_primo = True
  for i in range(2, n):
    if n % i == 0:
      eh_primo = False
      break
  if eh_primo == True:
    lista.append(n)
print(f"Números primos: {lista}")

numeros_primos = []

while True:
    try:
        valor = int(input("Informe um valor para descobrir os primos entre 1 e valor: "))
        if valor > 0:
            break  # sai do loop se for válido
        else:
            print("O número deve ser maior que zero!")
    except ValueError:
        print("Erro! Digite um número válido.")

# Aqui já se tem um valor válido, então faz os loops dos primos
for n in range(2, valor + 1):
    eh_primo = True
    for i in range(2, n):
        if n % i == 0:
            eh_primo = False
            break
    if eh_primo:
        numeros_primos.append(n)

print(numeros_primos)

numero_qqr = int(input("Informe um número para criar uma lista contendo todos os primos até esse número: "))

while numero_qqr <= 0:
  numero_qqr = int(input("Informe um número para criar uma lista contendo todos os primos até esse número: "))
primos = []
for i in range(2, numero_qqr + 1):
  primo = True
  for valor in range(2, i):
    if i % valor == 0:
      primo = False
      break
  else:
    primos.append(i)
print(primos)

anyy = int(input("Put any number to discover the prime numbers behind him: "))
list_of_primes = []

while anyy <= 0:
  anyy = int(input("Put any number to discover the prime numbers behind him: "))

for i in range(2, anyy + 1):
  prime = True
  for j in range(2, i):
    if i % j == 0:
      prime = False
      break
  if prime:
    list_of_primes.append(i)

print(f"The prime numbers are: {list_of_primes}")

any = 0
numbers = []
while any <= 0:
  any = int(input("Please inform a number to discover the prime numbers behind the number: "))

for i in range(2, any + 1):
  prime = True
  for u in range(2, i):
    if i % u == 0:
      prime = False
      break
  if prime:
    numbers.append(i)

print(numbers)

"""#### Questão 6
Escreva um programa que peça uma data informando o dia, mês e ano e determine se ela é uma data válida para uma análise.
"""

program = True

while program:
  """dia, mes, ano = input("Informe a data (dd/mm/aaaa): ").split("/")
      dia = int(dia)
      mes = int(mes)
      ano = int(ano)"""
  data = []

  data = input("Informe a data (dd/mm/aaaa): ")
  partes = data.split("/")

  dia = int(partes[0])
  mes = int(partes[1])
  ano = int(partes[2])

  while 30 <= dia <= 1:
    dia = int(input("Informe um dia válido! "))
    if 30 >= dia >= 1:
      data.append(dia)
    else:
      break
  while 12 <= mes >= 1:
    mes = int(input("Informe um mês válido! "))
  if 12 >= mes >= 1:
    data.append(mes)
  else:
    break
  while 99999 <= mes >= 1:
    ano = int(input("Informe um ano válido! "))
  if 99999 >= data_analise[2] >= 1:
      data.append(data[2])
  else:
    break
  if len(data) == 3:
    print(f"Data válida! {data}")
    program = False

while True:
  entrada = input("Informe uma data válida dd/mm/aaaa: ")
  data_validacao = entrada.split("/")
  # print(data_validacao) depuração

  dia = int(data_validacao[0])
  mes = int(data_validacao[1])
  ano = int(data_validacao[2])
  # print(data_validacao) depuração

  if 31 >= dia >= 1 and 12 >= mes >= 1 and ano > 0:
    break
  else:
    print("Informe uma data no formato dd/mm/aaaa!")
print(f"Dia: {dia}\nMês: {mes}\nAno:{ano}")

"""### Momento dos projetos

#### Questão 7
Para um estudo envolvendo o nível de multiplicação de bactérias em uma colônia, foi coletado o número de bactérias multiplicadas por dia, com base em um processo de duplicação diária e pode ser observado a seguir: `[1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]`. Tendo esses valores, faça um código que gere uma lista contendo o percentual de crescimento de bactérias por dia, comparando o número de bactérias em cada dia com o número de bactérias do dia anterior. Dica: para calcular o percentual de crescimento usamos a seguinte equação: `100 * (amostra_atual - amostra_passada) / (amostra_passada)`.
"""

bac = [1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]
bacterias = []

for i in range(1, len(bac)):
  bacterias.append((100 * (bac[i] - bac[i-1])) / bac[i-1])

bacterias

bacterias = [1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]
crescimentos = []
for n in range(1, len(bacterias)):
  crescimentos.append(100 * (bacterias[n] - bacterias[n-1]) / (bacterias[n-1]))
crescimentos

bacterias = [1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]
crescimentos = []

for n in range(1, len(bacterias)):
  crescimentos.append((100 * (bacterias[n] - bacterias[n-1])) / bacterias[n-1])

crescimentos

"""#### Questão 8
Para uma seleção de produtos alimentícios, precisamos separar o conjunto de IDs dados por números inteiros, sabendo que os produtos com ID par são doces e os com ID ímpar são amargos. Monte um código que colete 10 IDs. Depois, calcule e mostre a quantidade de produtos doces e amargos.
"""

doces = []
amargos = []

for i in range(1, 11):
  id = int(input("Informe o id do alimento: "))
  if id % 2 == 0:
    doces.append(id)
  else:
    amargos.append(id)

print(f"Doces: {len(doces)}")
print(f"Amargos: {len(amargos)}")

"""#### Questão 9
Desenvolva um programa que informa a nota de um aluno de acordo com suas respostas. Ele deve pedir a resposta de um aluno para cada questão e é preciso verificar se a resposta foi igual ao gabarito. Cada questão vale um ponto e existem alternativas:  A, B, C ou D.
```
Gabarito da Prova:
01 - D
02 - A
03 - C
04 - B
05 - A
06 - D
07 - C
08 - C
09 - A
10 - B
```
"""



gabarito = ["D", "A", "C", "B", "A", "D", "C", "C", "A", "B"]
letras = []
acertos = 0

for i in range(len(gabarito)):
  letra = input(f"Informe a letra da {i+1} questão: ")
  while letra.upper() not in ["A", "B", "C", "D"]:
    letra = input(f"Informe a letra da {i+1} questão: ")
  letras.append(letra.upper())
  if letra.upper() == gabarito[i]:
    acertos += 1
print(f"Você acertou {acertos} de {len(gabarito)} questões.")
print(f"Gabarito: {gabarito}")
print(f"Suas respostas: {letras}")

"""#### Questão 10
Um instituto de meteorologia deseja fazer um estudo de temperatura média de cada mês do ano. Para isso, você precisa fazer um código que colete e armazene essas temperaturas médias em uma lista. Depois, calcule a média anual das temperaturas e mostre todas as temperaturas acima da média anual, e em que mês elas ocorreram, mostrando os meses por extenso: Janeiro, Fevereiro, etc.
"""

temperaturas = []
for mes in range(1, 13):
  temperatura = int(input(f"Informe a temperatura do mês {mes}: "))
  temperaturas.append(temperatura)
media_temps = (sum(temperaturas)) / len(temperaturas)

meses = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Novembro", "Dezembro"]

for i in range(len(temperaturas)):
  if temperaturas[i] > media_temps:
    print(f"Meses em que a temperatura foi maior:\n{meses[i]}: {temperaturas[i]}ºC")
print(f"Média de temperaturas: {media_temps}")

"""#### Questão 11
Uma empresa de e-commerce está interessada em analisar as vendas dos seus produtos. Os dados das vendas foram armazenados em um dicionário:
```
{'Produto A': 300, 'Produto B': 80, 'Produto C': 60,
 'Produto D': 200, 'Produto E': 250, 'Produto F': 30}
```
Escreva um código que calcule o total de vendas e o produto mais vendido.
"""

dicionario = {'Produto A': 300, 'Produto B': 80, 'Produto C': 60,
 'Produto D': 200, 'Produto E': 250, 'Produto F': 30}

sum(dicionario.values())
maior = max(dicionario.values())
print(maior)

"""#### Questão 12
Uma pesquisa de mercado foi feita para decidir qual design de uma marca infantil mais agrada crianças. A pesquisa foi feita e o votos computados podem ser observados abaixo:
```
'''
Tabela de votos da marca
Design 1 - 1334 votos
Design 2 - 982 votos
Design 3 - 1751 votos
Design 4 - 210 votos
Design 5 - 1811 votos
'''
```
Adapte os dados fornecidos a você para uma estrutura de dicionário e a partir dele, informe o design vencedor e a porcentagem de votos recebidos.

"""

pesquisa = {"Design 1": 1334, "Design 2:": 982, "Design: 3": 1751, "Design 4": 210, "Design 5": 1811}
porcentagens = []
soma = sum(pesquisa.values())
for chave, valor in pesquisa.items():
  valores = (valor / soma) * 100
  porcentagens.append(valores)


print(f"Porcentagens: {porcentagens}")

"""#### Questão 13
Os funcionários de um setor da empresa que você trabalha vão receber um abono correspondente a 10% do seu salário devido ao ótimo desempenho do time. O setor financeiro solicitou sua ajuda para a verificação das consequências financeiras que esse abono irá gerar nos recursos. Assim, foi encaminhada para você uma lista com os salários que receberão o abono: `[1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]`. O abono de cada funcionário não pode ser inferior a 200. Em código, transforme cada um dos salários em chaves de um dicionário e o abono de cada salário no elemento. Depois, informe o total de gastos com o abono, quantos funcionários receberam o abono mínimo e qual o maior valor de abono fornecido.

"""

salarios = [1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]
menores = 0
abono = 0
salarios_dict = {}
abonos = []

for salario in salarios:
  abono = salario * 0.10
  if abono <= 200:
    abono = 200
    menores += 1
  abonos.append(abono)
  salarios_dict[salario] = abono

print(f"O total de gastos com abono foi {sum(abonos)}, {menores} funcionários receberam o abono mínimo e o maior abono foi de {max(abonos):.2f}")

salaries = [1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]
abonos = []
salaries_dict = {}
minimum = 0

for salary in salaries:
  abono = salary * 0.10
  if abono < 200:
    minimum += 1
    abono = 200
  abonos.append(abono)
  salaries_dict[salary] = abono
print(f"O total de gastos com abono foi: {sum(abonos)}, houveram {minimum} funcionários com abono mínimo e o maior abono foi {max(abonos):.2f}")

"""#### Questão 14
Uma equipe de cientistas de dados está estudando a diversidade biológica em uma floresta. A equipe fez a coleta de informações sobre o número de espécies de plantas e animais em cada área da floresta e armazenaram essas informações em um dicionário. Nele, a chave descreve a área dos dados e os valores nas listas correspondem às espécies de plantas e animais nas áreas, respectivamente.
```
{'Área Norte': [2819, 7236],
 'Área Leste': [1440, 9492],
 'Área Sul': [5969, 7496],
 'Área Oeste': [14446, 49688],
 'Área Centro': [22558, 45148]}
```
Escreva um código para calcular a média de espécies por área e identificar a área com a maior diversidade biológica. Dica: use as funções built-in [`sum()`](https://docs.python.org/3/library/functions.html#sum) e [`len()`](https://docs.python.org/3/library/functions.html#len).

"""

areas = {'Área Norte': [2819, 7236],
 'Área Leste': [1440, 9492],
 'Área Sul': [5969, 7496],
 'Área Oeste': [14446, 49688],
 'Área Centro': [22558, 45148]}

diversidades = {}
plantas = []
animais = []

for key, (planta, animal) in areas.items():
  diversidade = planta + animal
  plantas.append(planta)
  animais.append(animal)
  diversidades[key] = diversidade
  area_maior = max(diversidades, key=diversidades.get)
print(f"A média de espécies é:\nPlantas: {sum(plantas)/len(plantas)}\nAnimais: {sum(animais)/len(animais)}\nA área com maior diversidade biológica é a {area_maior}")

biology_dictionary = {'Área Norte': [2819, 7236],
 'Área Leste': [1440, 9492],
 'Área Sul': [5969, 7496],
 'Área Oeste': [14446, 49688],
 'Área Centro': [22558, 45148]}

animals = []
plants = []
largest = ""
greater = 0

for key, (animal, plant) in biology_dictionary.items():
  animals.append(animal)
  plants.append(plant)
  if plant > greater:
    greater = plant
    largest = key

print(f"Média de espécies por área: {sum(animals)/len(animals)}\nA área com maior diversidade biológica é: {largest}")

"""#### Questão 15
O setor de RH da sua empresa te pediu uma ajuda para analisar as idades dos funcionários de 4 setores da empresa. Para isso, ele te forneceu os seguintes dados:
```
{'Setor A': [22, 26, 30, 30, 35, 38, 40, 56, 57, 65],
 'Setor B': [22, 24, 26, 33, 41, 49, 50, 54, 60, 64],
 'Setor C': [23, 26, 26, 29, 34, 35, 36, 41, 52, 56],
 'Setor D': [19, 20, 25, 27, 34, 39, 42, 44, 50, 65]}
```
Sabendo que cada setor tem 10 funcionários, construa um código que calcule a média de idade de cada setor, a idade média geral entre todos os setores e quantas pessoas estão acima da idade média geral.

"""

funcionarios = {'Setor A': [22, 26, 30, 30, 35, 38, 40, 56, 57, 65],
 'Setor B': [22, 24, 26, 33, 41, 49, 50, 54, 60, 64],
 'Setor C': [23, 26, 26, 29, 34, 35, 36, 41, 52, 56],
 'Setor D': [19, 20, 25, 27, 34, 39, 42, 44, 50, 65]}

idades = 0
contador = 0
medias = {}

for setor, lista_idades in funcionarios.items():
  medias[setor] = sum(funcionarios[setor])/(len(funcionarios[setor]))
  for i in lista_idades:
    idades += i
    contador += 1
media_geral = idades/contador

i = 0
maiores = 0

for setor in funcionarios.keys():
  for i in funcionarios[setor]:
    if i > media_geral:
      maiores += 1

print(f"À seguir, confira a média de idade por setor:\nA: {medias['Setor A']}\nB: {medias['Setor B']}\nC: {medias['Setor C']}\nD: {medias['Setor D']}\nMédia geral: {media_geral:.2f}\nNúmero de funcionários acima da média: {maiores} ({(maiores/contador)*100}%)\nNúmero total de funcionários: {contador}")

"""### Questão 16
Uma escola está analisando o desempenho de suas 3 turmas no último semestre. Cada turma tem 8 alunos, e você recebeu as notas finais de cada turma:

```
    'Turma A': [7.5, 8.0, 6.5, 9.0, 7.0, 8.5, 7.8, 6.0],
    'Turma B': [5.5, 6.0, 7.0, 8.0, 6.5, 7.5, 8.5, 9.0],
    'Turma C': [9.0, 8.5, 9.5, 8.0, 7.5, 9.0, 8.8, 9.2]
```

Construa um código que:

- Calcule a média de cada turma
- Identifique qual turma teve a maior média
- Conte quantos alunos no total (das 3 turmas) tiraram nota acima de 8.0
"""

turmas = {'Turma A': [7.5, 8.0, 6.5, 9.0, 7.0, 8.5, 7.8, 6.0],
    'Turma B': [5.5, 6.0, 7.0, 8.0, 6.5, 7.5, 8.5, 9.0],
    'Turma C': [9.0, 8.5, 9.5, 8.0, 7.5, 9.0, 8.8, 9.2]}

notas_acima = 0
medias_dict = {}
media = 0

for turma, lista_medias in turmas.items():
  for nota in lista_medias:
    if nota > 8:
      notas_acima += 1
  medias_dict[turma] = sum(lista_medias)/(lista_medias)

indice_maior = max(medias_dict, key = medias_dict.get)

print(f"A média de cada uma das turmas foi: {medias_dict}.\nA turma que obteve a maior média foi a {indice_maior}.\nForam {notas_acima} alunos com nota acima de 8.")

"""Questão 17
Você está analisando dados de vendas mensais de uma loja ao longo de um ano. Os valores em reais estão na lista abaixo, onde cada posição representa um mês (Janeiro = índice 0, Fevereiro = índice 1, etc):
```
[12000, 15000, 18000, 16000, 14000, 17000, 19000, 21000, 23000, 20000, 22000, 25000]
```
Construa um código que:

- Calcule a variação percentual de vendas de cada mês em relação ao mês anterior (use a fórmula: 100 * (atual - anterior) / anterior)
- Identifique em qual mês houve a maior queda percentual (variação negativa)
- Mostre o percentual dessa queda

Dica: O primeiro mês (Janeiro) não tem mês anterior, então a lista de variações terá 11 elementos.
"""

vendas = [12000, 15000, 18000, 16000, 14000, 17000, 19000, 21000, 23000, 20000, 22000, 25000]
meses_com_variacao = []
mes = 0
for i in range(1, len(vendas)):
  mes = (100 * (vendas[i] - vendas[i-1]) / vendas[i-1])
  meses_com_variacao.append(mes)
menor_valor = min(meses_com_variacao)
indice_menor = meses_com_variacao.index(menor_valor)

# indice_menor = meses_com_variacao.index(min(meses_com_variacao))

print(f"O mês {indice_menor + 1} teve a maior queda de {menor_valor:.2f}%")

"""### Questão 18
Você está analisando o estoque de uma loja de eletrônicos. O sistema forneceu os seguintes dados sobre produtos e suas quantidades em estoque:
```
estoque = {
    'Notebook': 15,
    'Mouse': 45,
    'Teclado': 23,
    'Monitor': 8,
    'Webcam': 12,
    'Headset': 31
}
```
Construa um código que:

- Identifique quais produtos têm estoque abaixo de 20 unidades
- Calcule o total de itens em estoque (soma de todas as quantidades)
- Mostre qual produto tem o maior estoque
"""

estoque = {
    'Notebook': 15,
    'Mouse': 45,
    'Teclado': 23,
    'Monitor': 8,
    'Webcam': 12,
    'Headset': 31
}

goods = {}
elements = 0

for key, element in estoque.items():
  elements += element
  if element < 20:
    goods[key] = element

print(f"Os produtos com estoque abaixo de 20 unidades são:\n{goods}\nO total de itens em estoque é: {elements}\nE o procuto com maior estoque é o {max(estoque, key=estoque.get)}.")

"""### Questão 19
Um professor registrou as notas de 3 provas de cada aluno. Os dados estão organizados assim:
```
alunos = {
    'Ana': [7.5, 8.0, 9.0],
    'Bruno': [6.0, 7.0, 6.5],
    'Carlos': [9.0, 8.5, 9.5],
    'Diana': [5.5, 6.0, 7.0],
    'Eduardo': [8.0, 8.5, 8.0]
}
```
Construa um código que:

- Calcule a média final de cada aluno
- Identifique quantos alunos foram aprovados (média ≥ 7.0)
- Mostre o nome do aluno com a maior média
"""

students = {
    'Ana': [7.5, 8.0, 9.0],
    'Bruno': [6.0, 7.0, 6.5],
    'Carlos': [9.0, 8.5, 9.5],
    'Diana': [5.5, 6.0, 7.0],
    'Eduardo': [8.0, 8.5, 8.0]
}

avgs = []
averages = {}
approves = 0

for student, grades in students.items():
  avg = (sum(grades)/len(grades))
  if avg >= 7.0:
    approves += 1
  avgs.append(avg)
  averages[student] = avg
better = max(averages, key = averages.get)

print([f"Average note: {avg:.2f}" for avg in avgs])
print(f"We have {approves} approved students.\nThe better student is {better} with {max(avgs):.2f} average.")

"""### Questão 20
Você está analisando a evolução do número de seguidores de uma página nas redes sociais ao longo de 6 meses:
```seguidores = [1200, 1450, 1380, 1520, 1680, 1590]```
Construa um código que:

- Calcule a variação absoluta (diferença) de seguidores entre cada mês e o anterior (ex: mês 2 - mês 1)
- Identifique em qual mês houve a maior perda de seguidores (variação negativa)
- Calcule a variação total (último mês - primeiro mês)

Dica: A lista de variações terá 5 elementos (não há mês anterior ao primeiro).
"""

seguidores = [1200, 1450, 1380, 1520, 1680, 1590]
variacoes = []
variacao = 0
variacao_total = 0

for i in range(1, len(seguidores)):
  variacao = (seguidores[i] - seguidores[i-1])
  variacoes.append(variacao)
indice_menor = min(variacoes)
variacao_total = (seguidores[-1] - seguidores[0])
menor_mes = variacoes.index(indice_menor)

print(f"A diferença absoluta de cada mês é {variacoes} mês a mês, a maior perda de seguidores foi no mes {menor_mes+2} e a variação total foi de {variacao_total:.2f}.")